project_name: GNet
env:
- GO111MODULE=on
before:
  hooks:
  - go mod download
builds:
- id: gbchian-darwin-amd64
  ldflags: -s -w -X gbchain-org/go-gbchain.Version={{.Version}} -X gbchain-org/go-gbchain.BuildDate={{.Date}} -X gbchain-org/go-gbchain.CommitHash={{ .ShortCommit }}
  binary: gbchain
  env:
  - CGO_ENABLED=1
  - CC=o64-clang
  - CXX=o64-clang++
  main: ./cmd/gbchian/
  goos:
  - darwin
  goarch:
  - amd64
- id: gbchian-linux-amd64
  ldflags: -s -w -X gbchain-org/go-gbchain.Version={{.Version}} -X gbchain-org/go-gbchain.BuildDate={{.Date}} -X gbchain-org/go-gbchain.CommitHash={{ .ShortCommit }}
  binary: gbchain
  env:
  - CGO_ENABLED=1
  main: ./cmd/gbchain/
  goos:
  - linux
  goarch:
  - amd64

- id: gbchian-windows-amd64
  ldflags: -s -w -X gbchain-org/go-gbchain.Version={{.Version}} -X gbchain-org/go-gbchain.BuildDate={{.Date}} -X gbchain-org/go-gbchain.CommitHash={{ .ShortCommit }}
  binary: gbchian
  env:
  - CGO_ENABLED=1
  - CC=x86_64-w64-mingw32-gcc
  - CXX=x86_64-w64-mingw32-g++
  main: ./cmd/gbchian/
  goos:
  - windows
  goarch:
  - amd64
archives:
- format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  name_template: "{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}"
  wrap_in_directory: true
  replacements:
    macOS: darwin
    Linux: linux
    Windows: windows
  files:
  - README.md
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
